language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install PyYAML
  - pip install coveralls
script:
  - pytest
after_success:
  - coverage run --source=worldgen -m pytest
  - coveralls